version: '3.8'

services:
  mysql_db:
    build: 
      context: ./db
    container_name: mysql-service
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./db/databasestructure.sql:/docker-entrypoint-initdb.d/databasestructure.sql 
    networks:
      - my-network
  back:
    build: 
      context: ./Backend
    container_name: appback
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
    networks:
      - my-network
  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - 80:80
    networks:
      - my-network
networks:
  my-network:
volumes:
  mysql_data: