# Usa la imagen base de Nginx
FROM nginx:alpine

# Copia el archivo de configuración de Nginx al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto en el que Nginx escuchará
EXPOSE 80